export const countries = [
    "Afganistán",
    "Albania",
    "Alemania",
    "Andorra",
    "Angola",
    "Anguila",
    "Antigua y Barbuda",
    "Antártida",
    "Arabia Saudí",
    "Argelia",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaiyán",
    "Bahamas",
    "Bahrein",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belice",
    "Benín",
    "Bermudas",
    "Bhután",
    "Bolivia",
    "Bonaire, San Eustaquio y Saba",
    "Bosnia-Herzegovina",
    "Botswana",
    "Bouvet, Isla",
    "Brasil",
    "Brunei Darussalam",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Bélgica",
    "Cabo Verde",
    "Caimán, Islas",
    "Camboya",
    "Camerún",
    "Canadá",
    "Centroafricana, República",
    "Chad",
    "Chile",
    "China",
    "Chipre",
    "Christmas, isla",
    "Cocos (Keeling), islas",
    "Colombia",
    "Comores",
    "Congo",
    "Congo, República democrática del",
    "Cook, Islas",
    "Corea, República de",
    "Corea, República popular democrática de",
    "Costa Rica",
    "Costa de Marfil",
    "Croacia",
    "Cuba",
    "Curazao",
    "Dinamarca",
    "Djibouti",
    "Dominica",
    "Ecuador1",
    "Egipto",
    "El Salvador",
    "Emiratos árabes unidos",
    "Eritrea",
    "Eslovaquia",
    "Eslovenia",
    "España",
    "Estados Unidos",
    "Estonia",
    "Etiopía",
    "Falkland (Malvinas), Islas",
    "Federación Rusa",
    "Feroe, Islas",
    "Fiji",
    "Filipinas",
    "Finlandia",
    "Francia",
    "Gabón",
    "Gambia",
    "Georgia",
    "Georgia del Sur e Islas Sandwich del Sur",
    "Ghana",
    "Gibraltar",
    "Granada",
    "Grecia",
    "Groenlandia",
    "Guadalupe",
    "Guam",
    "Guatemala",
    "Guayana",
    "Guernsey",
    "Guinea",
    "Guinea ecuatorial",
    "Guinea-Bissau",
    "Guyana francesa",
    "Haití",
    "Heard y McDonald, Islas",
    "Honduras",
    "Hong-Kong",
    "Hungría",
    "India",
    "Indonesia",
    "Iraq",
    "Irlanda",
    "Irán, República islámica de",
    "Islandia",
    "Israel",
    "Italia",
    "Jamaica",
    "Japón",
    "Jersey",
    "Jordania",
    "Kazajstán",
    "Kenia",
    "Kirguistán",
    "Kiribati",
    "Kuwait",
    "Laos, República democrática popular de",
    "Lesotho",
    "Letonia",
    "Liberia",
    "Libia, Jamahiriya árabe",
    "Liechtenstein",
    "Lituania",
    "Luxemburgo",
    "Líbano",
    "Macao",
    "Macedonia, antigua república yugoslava de",
    "Madagascar",
    "Malasia",
    "Malawi",
    "Maldivas",
    "Mali",
    "Malta",
    "Man, Isla de",
    "Marianas del Norte, Islas",
    "Marruecos",
    "Marshall, Islas",
    "Martinica",
    "Mauricio",
    "Mauritania",
    "Mayotte",
    "Micronesia, Estados federados de",
    "Moldavia, República de Moldova",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Mozambique",
    "Myanmar",
    "Méjico",
    "Mónaco",
    "Namibia",
    "Nauru",
    "Nepal",
    "Nicaragua",
    "Nigeria",
    "Niué",
    "Norfolk, Isla",
    "Noruega",
    "Nueva Caledonia",
    "Nueva Zelanda",
    "Níger",
    "Océano Índico, Territorio británico del",
    "Omán",
    "Pakistán",
    "Palau",
    "Palestina, Territorio ocupado de",
    "Panamá",
    "Papúa Nueva Guinea",
    "Paraguay",
    "Países Bajos",
    "Perú",
    "Pitcairn",
    "Polinesia francesa",
    "Polonia",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Reino Unido",
    "República Checa",
    "República Dominicana",
    "Reunión",
    "Ruanda",
    "Rumanía",
    "Sahara occidental",
    "Salomón, Islas",
    "Samoa",
    "Samoa americana",
    "San Bartolomé",
    "San Cristóbal y Nieves",
    "San Marino",
    "San Martín (parte francesa)",
    "San Martín (parte holandesa)",
    "San Pedro y Miquelón",
    "San Vicente y Granadinas",
    "Santa Helena",
    "Santa Lucía",
    "Santa Sede (Estado de la Ciudad del Vaticano)",
    "Santo Tomé y Príncipe",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leona",
    "Singapur",
    "Siria, República árabe",
    "Somalia",
    "Sri Lanka",
    "Sudáfrica",
    "Sudán",
    "Sudán del Sur",
    "Suecia",
    "Suiza",
    "Suriname",
    "Svalbard e isla Jan Mayen",
    "Swazilandia",
    "Tailandia",
    "Taiwan, Provincia de China",
    "Tanzania, República unida de",
    "Tayikistán",
    "Territorios Australes franceses",
    "Timor oriental",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad y Tobago",
    "Turcos y Caicos, Islas",
    "Turkmenistán",
    "Turquía",
    "Tuvalu",
    "Túnez",
    "Ucrania",
    "Uganda",
    "Ultramarinas de los Estados Unidos, Islas",
    "Uruguay",
    "Uzbekistán",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "Vírgenes (USA), Islas",
    "Vírgenes británicas, Islas",
    "Wallis y Futuna",
    "Yemen",
    "Zambia",
    "Zimbabwe",
    "Åland, Islas"
]