export const personaFisicaInitialValues = {
    datosPrincipalesFisicas: {
        nombre: "",
        apellido: "",
        tipoID: "",
        id: "",
    },
    datosFiscales: {
        tipoCodigo: "",
        cuit: "",
        tipoResponsableIVA: "",
        tipoResponsableGanancias: "",
    },
    datosPersonales: {
        fechaNacimiento: "",
        sexo: "",
        estadoCivil: "",
        idioma: "",
        nacionalidad: "",
        paisResidencia: "",
        paisOrigen: "",
        lugarNacimiento: "",
        cie: "",
        actividad: "",
    },
    medioComunicacion: {
        tipo: "",
        medio: "",
        uso: "",
        notas: "",
    },
    domiciliosUrbanos: [],
    // domiciliosUrbanos: {
    //     uso: "",
    //     barrio: "",
    //     calle: "",
    //     numero: 0,
    //     torre: "",
    //     piso: 0,
    //     departamento: "",
    //     lugar: "",
    //     codigoPostal: "",
    //     notas: "",
    // },
    cuentaBancaria: [],
    // cuentaBancaria: {
    //     cbu: "",
    //     alias: "",
    //     interbanking: true,
    //     tipo: "",
    //     moneda: "",
    //     numero: "",
    //     denominacion: "",
    //     uso: "",
    //     notas: "",
    //     tipoID: "",
    // },
    cuentaBancariaExterior: [],
    // {
    //     cuenta: "",
    //     moneda: "",
    //     banco: "",
    //     denominacion: "",
    //     direccion: "",
    //     holderType: "",
    //     accountType: "",
    //     nroBancoABA: "",
    //     idSWIFT: "",
    //     notas: "",
    // },
    datosConyuge: {
        nombre: "",
        apellido: "",
        tipoID: "",
        id: "",
        tipoFiscal: "",
        claveFiscal: "",
    },
    infoPatrimonial: [],
    // infoPatrimonial: {
    //     fecha: "",
    //     patrimonio: 0,
    //     ingresos: 0,
    //     inversion: 0,
    //     procedenciaFondos: "",
    //     observaciones: "",
    //     fondeo: [],
    // },
    actividadPersona: [],
    // actividadPersona: {
    //     actividad: "",
    //     rubro: "",
    //     puesto: "",
    //     departamento: "",
    //     organizacion: "",
    //     inicio: "",
    //     fin: "",
    //     observaciones: "",
    //     codigoTipoActividad: "",
    // },
    declaracionesPF: {
        expuestaPoliticamente: false,
        detalleExpPoliticamente: "",
        sujetoObligado: false,
        numeroInscripcion: 0,
        sujetoObligadoUIF: "",
        personaEEUU: false,
        observacionesFATCA: "",
    },
}
